baseURL = 'https://michaelgainyo.github.io/'
languageCode = 'en-us'
title = '%_'
theme="archie"
paginate=12
[params]
    mode="light" # color-mode → light,dark,toggle or auto
    customcss = ["css/base.css"]
[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/michaelgainyo/"
[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/michaelgainyo/"

	